### ISSUE TITLE
Do roboty - includes

### ISSUE THREAD

**Issue by websafe** [LOCOSP/interface_web_home_automation#11]
W głównym katalogu utwórz podkatalog `includes` i do niego powrzucaj takie rzeczy jak:

 + `header.php`,
 + `footer.php` (nie ma, ale utwórz, bo będzie potrzebny - czytaj dalej),
 + `funkcje.php`,
 + `navbar.php`.

Ten cały `javascript.php` to zmień mu nazwę na `footer.php` i wrzuć do `includes/`.

A następnie we wszystkich plikach, w których ładujesz `header.php`, zamień:

~~~~
<?php include_once 'header.php'; ?>
~~~~

na

~~~~
<?php require 'includes/header.php'; ?>
~~~~

`require`, bo przecież nagłówek jest **WYMAGANY** bo bez niego się posypie, więc bez egzotyki z `include_once` proszę ;)

Następnie wszędzie, gdzie w stopce robisz:

~~~~
<?php include_once 'javascript.php'; ?>
~~~~

zamień to na:

~~~~
<?php require 'includes/footer.php'; ?>
~~~~

I dalej, wszędzie gdzie ładujesz `navbar.php`, zamień:

~~~~
<?php require_once 'navbar.php'; ?>
~~~~

na

~~~~
<?php require 'includes/navbar.php'; ?>
~~~~

**Comment by LOCOSP** [comment]
zrobione.
