### ISSUE TITLE
config.php 

### ISSUE THREAD

**Issue by websafe** [LOCOSP/interface_web_home_automation#12]
Głupi jest ten `config.php` walający się w głównym katalogu. 
Przenieś go do katalogu `config/` a następnie wszystkie odwołania do niego popoprawiaj na

~~~~
<?php require 'config/config.php'; ?>
~~~~

**Comment by LOCOSP** [comment]
zrobione.

**Comment by websafe** [comment]
NAwet bym nie pamietał, że taki ticket otworzyłem, bo go zamknąłeś :dancer:
