### ISSUE TITLE
Smart Engine

### ISSUE THREAD

**Issue by LOCOSP** [LOCOSP/interface_web_home_automation#2]
Mogę stworzyć listę poleceń dotychczas używanych w automatyce a potrzebowałbym silnik który używając istniejących poleceń tworzył ich łańcuchy jedno względem drugiego ( jeśli TVOn to GALERIAOff i SIDELIGHTOn ), ewentualnie w formie terminarza ( godzina 07:00 05.08.2014 RADIOOn czekaj 5 minut RADIOOff ).

English:
I can make a list of used commands in my automation, but need an engine to make them smart :)
example:
if TVOn turn GALLERYOff and SIDELIGHTOn it can depends on daylight time..
or like timetable on 07:00 AM 05.08.2014 RADIOOn wait 5 minutes and RADIOOff.

**Comment by websafe** [comment]
To zrobimy scenami.

**Comment by websafe** [comment]
Zamknij śmiało.
