### ISSUE TITLE
config

### ISSUE THREAD

**Issue by websafe** [LOCOSP/interface_web_home_automation#4]
http://pastebin.com/LaQc4rkj

**Comment by websafe** [comment]
~~~~
{
    "amplifier": {
        "power": {
            "on": "irsend send_once amplifier on",
            "off": "irsend send_once amplifier off"
        }
    }
}
~~~~

**Comment by websafe** [comment]
{
    "amplifier": {
        "power": {
            "on": "irsend send_once amplifier on",
            "off": "irsend send_once amplifier off"
        },
        "volume": {
            "up": "irsend send_once amplifier on",
            "down": "irsend send_once amplifier off",
            "mute": "irsend send_once amplifier off",
        }
    }
}

**Comment by websafe** [comment]
`config/commands.json`

**Comment by LOCOSP** [comment]
begin remote



  name  amplifier

  bits           32

  flags SPACE_ENC

  eps            55

  aeps          100

  header       3536  1673

  one           423   378

  zero          423  1266

  ptrail        423

  pre_data_bits   16

  pre_data       0xBFFB

  gap          74384

  toggle_bit      0

  frequency     38000



      begin codes

          volume+                  0x00000000FAFFFBFE
          volume-                  0x00000000FAFF7B7E
          muting                   0x00000000FAFFB3B6
          channel^                 0x00000000FADFD3F6
          channelV                 0x00000000FADF5376
          tv/video                 0x00000000FEFF5F5E
          test                     0x00000000FAD790BD
          sfc                      0x00000000FAD7735E
          soundmode                0x00000000FAD7F2DF
          +                        0x00000000FAD7C2EF
          -                        0x00000000FAD7426F
          level                    0x00000000FAD782AF
          delay                    0x00000000FAD7022F
          DVDplay                  0x00000000F2FFAFA2
          DVDstop                  0x00000000F2FFFFF2
          DVDff                    0x00000000F2FFADA0
          DVDrew                   0x00000000F2FF6D60
          subwoofer                0x00000000FAFF5451
          display                  0x00000000F2FFB6BB
          V                        0x00000000F2FF9E93
          ^                        0x00000000F2FF5E53
          >                        0x00000000F2FFEEE3
          <                        0x00000000F2FF1E13
          enter                    0x00000000F2FFBEB3
          menu                     0x00000000F2FFFEF3
          topmenu                  0x00000000F2FF262B
          0                        0x00000000FADF6742
          9                        0x00000000FADFE7C2
          8                        0x00000000FADF1732
          7                        0x00000000FADF97B2
          6                        0x00000000FADF5772
          5                        0x00000000FADFD7F2
          4                        0x00000000FADF3712
          3                        0x00000000FADFB792
          2                        0x00000000FADF7752
          1                        0x00000000FADFF7D2
          >10                      0x00000000FADFDEFB
          directtuning             0x00000000FADFEECB
          tv                       0x00000000FAFF0603
          vcr                      0x00000000FAFF8683
          dvd                      0x00000000FAFF3A3F
          cd                       0x00000000FAFFD6D3
          tape                     0x00000000FAFF9693
          tunerband                0x00000000FAFFB6B3
          power                    0x00000000FAFF4346
          on                       0x00000000FAFF8386
          off                      0x00000000FAFF0306
          audiopower       0x00000000FAC7033E
      end codes

end remote

**Comment by LOCOSP** [comment]
zmieniłem:

begin remote



  name  amplituner

  bits           32

  flags SPACE_ENC

  eps            55

  aeps          100

  header       3536  1673

  one           423   378

  zero          423  1266

  ptrail        423

  pre_data_bits   16

  pre_data       0xBFFB

  gap          74384

  toggle_bit      0

  frequency     38000



      begin codes

          volumeup                 0x00000000FAFFFBFE
          volumedown               0x00000000FAFF7B7E
          volumemute               0x00000000FAFFB3B6
          channelup                0x00000000FADFD3F6
          channeldown              0x00000000FADF5376
          tv/video                 0x00000000FEFF5F5E
          test                     0x00000000FAD790BD
          sfc                      0x00000000FAD7735E
          soundmode                0x00000000FAD7F2DF
          +                        0x00000000FAD7C2EF
          -                        0x00000000FAD7426F
          level                    0x00000000FAD782AF
          delay                    0x00000000FAD7022F
          DVDplay                  0x00000000F2FFAFA2
          DVDstop                  0x00000000F2FFFFF2
          DVDff                    0x00000000F2FFADA0
          DVDrew                   0x00000000F2FF6D60
          subwoofer                0x00000000FAFF5451
          display                  0x00000000F2FFB6BB
          V                        0x00000000F2FF9E93
          ^                        0x00000000F2FF5E53
          >                        0x00000000F2FFEEE3
          <                        0x00000000F2FF1E13
          enter                    0x00000000F2FFBEB3
          menu                     0x00000000F2FFFEF3
          topmenu                  0x00000000F2FF262B
          0                        0x00000000FADF6742
          9                        0x00000000FADFE7C2
          8                        0x00000000FADF1732
          7                        0x00000000FADF97B2
          6                        0x00000000FADF5772
          5                        0x00000000FADFD7F2
          4                        0x00000000FADF3712
          3                        0x00000000FADFB792
          2                        0x00000000FADF7752
          1                        0x00000000FADFF7D2
          >10                      0x00000000FADFDEFB
          directtuning             0x00000000FADFEECB
          source-tv                0x00000000FAFF0603
          source-vcr               0x00000000FAFF8683
          source-dvd               0x00000000FAFF3A3F
          source-cd                0x00000000FAFFD6D3
          source-tape              0x00000000FAFF9693
          tunerband                0x00000000FAFFB6B3
          power                    0x00000000FAFF4346
          power-on                 0x00000000FAFF8386
          power-off                0x00000000FAFF0306
          audiopower               0x00000000FAC7033E
      end codes

end remote

**Comment by websafe** [comment]
Zamykamy.
