### ISSUE TITLE
Takie same parametry dla tellstick?

### ISSUE THREAD

**Issue by websafe** [LOCOSP/interface_web_home_automation#8]
W pliku
https://github.com/LOCOSP/interface_web_home_automation/blob/commands/config/commands.json

widzę identyczne polecenia dla różnych świateł:

~~~~
 "light-corner": {
    "power": {
        "off": "tdtool -f 1",
        "on": "tdtool -n 1"
    }
},
~~~~

i

~~~~
 "light-window": {
    "power": {
        "off": "tdtool -f 1",
        "on": "tdtool -n 1"
    }
}
~~~~

**Comment by LOCOSP** [comment]
Tak, obecnie obydwa switche ( dwie lampki ) odpalane są jedną komendą ...
